test:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Print success message
      run: echo "Tests passed. Everything is working fine!"
