name: Node.JS CI/CD

on:
  push:
    paths:
    - 'server/'
    branches: ["main"]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and run tests
      run: |
        npm install
        npm test
      working-directory: server

    - name: Build Docker image
      run: |
          docker build -t health-frontend .

    - name: Push Docker image to registry
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag health-frontend balavardhan/health-frontend
          docker push balavardhan/health-frontend
